import type { Metadata } from "next";
import { Inter, League_Gothic, Poppins } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] , weight: "500", variable: "--font-inter"});
const poppins300 = Poppins({ subsets: ["latin"] , weight: "300", variable: "--font-poppins300"});
const poppins400 = Poppins({ subsets: ["latin"] , weight: "400", variable: "--font-poppins400"});
const poppins600 = Poppins({ subsets: ["latin"] , weight: "600", variable: "--font-poppins600"});
const poppins700 = Poppins({ subsets: ["latin"] , weight: "700", variable: "--font-poppins700"});
const poppins900 = Poppins({ subsets: ["latin"] , weight: "900", variable: "--font-poppins900"});
const gothic = League_Gothic({ subsets: ["latin"] , weight: "400", variable: "--font-gothic"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins300.variable} ${poppins400.variable} ${poppins600.variable} ${poppins700.variable} ${poppins900.variable} ${gothic.variable}`}>{children}</body>
    </html>
  );
}
