# Generated by Django 5.0.5 on 2024-05-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='spotify_connection',
            field=models.BooleanField(default=False),
        ),
    ]
