# Generated by Django 5.0.5 on 2024-05-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser_spotify_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendationsearch',
            name='name',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
